### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by gsargent70** [nickbild/c64_watch#3]
Can't seem to get this to compile.  When I open the sketch it crashes with the following while trying to compile

Arduino: 1.8.13 (Windows 10), Board: "TTGO T-Watch, T-Watch-2020-V1, Enabled, Default (2 x 6.5 MB app, 3.6 MB SPIFFS), 2000000, None"

c64.c:1:18: fatal error: lvgl.h: No such file or directory

Multiple libraries were found for "WiFi.h"

compilation terminated.

 Used: C:\Users\Greg\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi

 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi

exit status 1

lvgl.h: No such file or directory

I have verified the path in the c64.c file is pointed to my document directory and that the file is indeed there but no luck.

**Comment by nickbild** [comment]
This is a bit difficult to troubleshoot on someone else's machine, but the error is clear: `lvgl.h: No such file or directory`.    My best guess is that there is an unescaped space or some other typo in the path that is preventing the compiler from seeing your include.

**Comment by gsargent70** [comment]
For anyone else that runs into this issue I had to fully qualify the path for the lvgl.h file.  for me this was

#include "C:/Users/Greg/Documents/Arduino/libraries/TTGO_TWatch_Library-1.1.0/src/lvgl/lvgl.h"

in the c64.c file.  Now onto the next compile issue.

I also had to change to the fully qualified path in the file c64_basic.c just like the path above.
